# 14 analysis — 2026 OpenAI vs DeepSeek campaign concat

Pre-test: 2025 tokens × 2026 prices, plus parked Fable. Post-test: live packs when they exist.

Family plots split thinking on vs off **within** OpenAI and DeepSeek (`hue=thinking`). Do not average on/off cells.

In [1]:
from pathlib import Path
import sys

ROOT = Path("..").resolve()
sys.path.insert(0, str(ROOT))

from src.memorybench.analysis.load_campaign import load_campaign_yaml
from src.memorybench.analysis.notebook_protocol import notebook_posttest, notebook_pretest
from src.memorybench.analysis.report import render_campaign, render_experiment

YAML = ROOT / "configs" / "analysis" / "campaign_2026_openai_deepseek.yaml"
camp = load_campaign_yaml(YAML)
print(camp.id, "->", YAML)

2026_openai_deepseek -> C:\home\research\Distillation\distillation\configs\analysis\campaign_2026_openai_deepseek.yaml

## Pre-test

Declared cells, hypotheses, and priced volume estimate. No pack required for the estimate when `cost.volume_from` is set.

In [2]:
notebook_pretest(camp, root=ROOT)

## Pre-test — 2026 OpenAI vs DeepSeek

Same sandwich as 2025_openai_deepseek with 2026 readers/writers (GPT-5.6 Terra, DeepSeek-V4). Frozen answer prompt qa_mem0_v1 and judge gpt-4o-mini. Anthropic (Claude Fable 5.1) is not in this matrix. Do not claim Mem0 paper Table 1–2 J. Smoke is 5 questions.

Config: `C:/home/research/Distillation/distillation/configs/analysis/campaign_2026_openai_deepseek.yaml`

### `smoke` — `locomo-2026-readers-openai-deepseek-smoke`
- subset: 1 conversation / 5 questions
- **not a scientific claim**
- expected cells: **2**
- expected questions / cell: **5**
- hypothesis: Terra and DeepSeek-V4 each return 5 predictions.
- hypothesis: Smoke cost is well under $1 (2025 full_context volumes × 5/1986).
- hypothesis: Not a quality claim.

### `baseline` — `locomo-2026-readers-openai-deepseek`
- scientific claim: yes (still not Mem0 paper J)
- expected cells: **4**
- expected questions / cell: **1986**
- hypothesis: Terra × full_context dominates (~$111 at pinned short-context rates).
- hypothesis: DeepSeek-V4 Flash full_context stays on the order of $10 off-peak.

### `writers` — `locomo-mem0-reader-2026-writers-openai-deepseek`
- scientific claim: yes (still not Mem0 paper J)
- expected cells: **4**
- expected questions / cell: **1986**
- hypothesis: Four writer cells stay near $12; frozen mini reader is ~$3 of that.
- hypothesis: Fable 5.1 is parked: same volumes at $10/$50 would add ~$611.

Parked (costed, not launched): Claude Fable 5.1

### Pre-test cost estimate

,experiment,memory_method,role,model,prompt_tokens,completion_tokens,usd_expected
0,baseline,rag,reader,gpt-5.6-terra,1859606,27322,4.047076
1,baseline,rag,judge,gpt-4o-mini,576372,30800,0.104936
2,baseline,full_context,reader,deepseek-v4-flash,56684657,11151,8.509389
3,baseline,full_context,judge,gpt-4o-mini,576930,30800,0.105020
4,baseline,rag,reader,deepseek-v4-flash,1880899,11381,0.288963
5,baseline,rag,judge,gpt-4o-mini,577597,30800,0.105120
6,baseline,full_context,reader,gpt-5.6-terra,55304493,27920,110.944026
7,baseline,full_context,judge,gpt-4o-mini,577061,30800,0.105039
8,writers,teacher_graph,reader,gpt-4o-mini,7016025,10291,1.058578
9,writers,teacher_graph,teacher,deepseek-v4-flash,541506,163446,0.179293
10,writers,teacher_graph,judge,gpt-4o-mini,576177,30800,0.104907
11,writers,teacher_session_summaries,reader,gpt-4o-mini,1039528,10651,0.162320
12,writers,teacher_session_summaries,teacher,gpt-5.6-terra,253618,277449,3.836624
13,writers,teacher_session_summaries,judge,gpt-4o-mini,576433,30800,0.104945
14,writers,teacher_graph,reader,gpt-4o-mini,898982,13665,0.143046
15,writers,teacher_graph,teacher,gpt-5.6-terra,526266,278528,4.394868
16,writers,teacher_graph,judge,gpt-4o-mini,578664,30800,0.105280
17,writers,teacher_session_summaries,reader,gpt-4o-mini,11834025,12301,1.782484
18,writers,teacher_session_summaries,teacher,deepseek-v4-flash,259167,53047,0.070703
19,writers,teacher_session_summaries,judge,gpt-4o-mini,577751,30800,0.105143
20,smoke,full_context,reader,deepseek-v4-flash,142711,28,0.021423
21,smoke,full_context,judge,gpt-4o-mini,1452,78,0.000265
22,smoke,full_context,reader,gpt-5.6-terra,139236,70,0.279312
23,smoke,full_context,judge,gpt-4o-mini,1453,78,0.000265

### Pre-test cost by stage

  experiment  n_cells_expected  scientific_claim  usd_expected usd_actual
0      smoke               2.0             False        0.3013       None
1   baseline               4.0              True      124.2096       None
2    writers               4.0              True       12.0482       None
3     parked               NaN             False      632.4180       None

### Parked (not launched)

,memory_method,role,model,cell_model,n_calls,prompt_tokens,completion_tokens,n_questions,experiment,usd,launched,parked_id,display_name
0,rag,reader,claude-fable-5-1,claude-fable-5-1,1986,1859606,27322,1986,baseline,19.962160,False,claude_fable,Claude Fable 5.1
1,rag,judge,gpt-4o-mini,claude-fable-5-1,1540,576372,30800,1986,baseline,0.104936,False,claude_fable,Claude Fable 5.1
2,full_context,reader,claude-fable-5-1,claude-fable-5-1,1986,55304493,27920,1986,baseline,554.440930,False,claude_fable,Claude Fable 5.1
3,full_context,judge,gpt-4o-mini,claude-fable-5-1,1540,577061,30800,1986,baseline,0.105039,False,claude_fable,Claude Fable 5.1
4,teacher_session_summaries,reader,claude-fable-5-1,claude-fable-5-1,1986,1039528,10651,1986,writers,10.927830,False,claude_fable,Claude Fable 5.1
5,teacher_session_summaries,teacher,claude-fable-5-1,claude-fable-5-1,272,253618,277449,1986,writers,16.408630,False,claude_fable,Claude Fable 5.1
6,teacher_session_summaries,judge,gpt-4o-mini,claude-fable-5-1,1540,576433,30800,1986,writers,0.104945,False,claude_fable,Claude Fable 5.1
7,teacher_graph,reader,claude-fable-5-1,claude-fable-5-1,1986,898982,13665,1986,writers,9.673070,False,claude_fable,Claude Fable 5.1
8,teacher_graph,teacher,claude-fable-5-1,claude-fable-5-1,272,526266,278528,1986,writers,19.189060,False,claude_fable,Claude Fable 5.1
9,teacher_graph,judge,gpt-4o-mini,claude-fable-5-1,1540,578664,30800,1986,writers,0.105280,False,claude_fable,Claude Fable 5.1
10,full_context,reader,claude-fable-5-1,claude-fable-5-1,5,139236,70,5,smoke,1.395860,False,claude_fable,Claude Fable 5.1
11,full_context,judge,gpt-4o-mini,claude-fable-5-1,4,1453,78,5,smoke,0.000265,False,claude_fable,Claude Fable 5.1

CostReport(scope='2026_openai_deepseek', by_cell=                memory_method     role              model         cell_model  \
0                         rag   reader      gpt-5.6-terra      gpt-5.6-terra
1                         rag    judge        gpt-4o-mini      gpt-5.6-terra
2                full_context   reader  deepseek-v4-flash  deepseek-v4-flash
3                full_context    judge        gpt-4o-mini  deepseek-v4-flash
4                         rag   reader  deepseek-v4-flash  deepseek-v4-flash
5                         rag    judge        gpt-4o-mini  deepseek-v4-flash
6                full_context   reader      gpt-5.6-terra      gpt-5.6-terra
7                full_context    judge        gpt-4o-mini      gpt-5.6-terra
8               teacher_graph   reader        gpt-4o-mini  deepseek-v4-flash
9               teacher_graph  teacher  deepseek-v4-flash  deepseek-v4-flash
10              teacher_graph    judge        gpt-4o-mini  deepseek-v4-flash
11  teacher_session_summaries   reader        gpt-4o-mini      gpt-5.6-terra
12  teacher_session_summaries  teacher      gpt-5.6-terra      gpt-5.6-terra
13  teacher_session_summaries    judge        gpt-4o-mini      gpt-5.6-terra
14              teacher_graph   reader        gpt-4o-mini      gpt-5.6-terra
15              teacher_graph  teacher      gpt-5.6-terra      gpt-5.6-terra
16              teacher_graph    judge        gpt-4o-mini      gpt-5.6-terra
17  teacher_session_summaries   reader        gpt-4o-mini  deepseek-v4-flash
18  teacher_session_summaries  teacher  deepseek-v4-flash  deepseek-v4-flash
19  teacher_session_summaries    judge        gpt-4o-mini  deepseek-v4-flash
20               full_context   reader  deepseek-v4-flash  deepseek-v4-flash
21               full_context    judge        gpt-4o-mini  deepseek-v4-flash
22               full_context   reader      gpt-5.6-terra      gpt-5.6-terra
23               full_context    judge        gpt-4o-mini      gpt-5.6-terra

    n_calls  prompt_tokens  completion_tokens  n_questions experiment  \
0      1986        1859606              27322         1986   baseline
1      1540         576372              30800         1986   baseline
2      1986       56684657              11151         1986   baseline
3      1540         576930              30800         1986   baseline
4      1986        1880899              11381         1986   baseline
5      1540         577597              30800         1986   baseline
6      1986       55304493              27920         1986   baseline
7      1540         577061              30800         1986   baseline
8      1986        7016025              10291         1986    writers
9       272         541506             163446         1986    writers
10     1540         576177              30800         1986    writers
11     1986        1039528              10651         1986    writers
12      272         253618             277449         1986    writers
13     1540         576433              30800         1986    writers
14     1986         898982              13665         1986    writers
15      272         526266             278528         1986    writers
16     1540         578664              30800         1986    writers
17     1986       11834025              12301         1986    writers
18      272         259167              53047         1986    writers
19     1540         577751              30800         1986    writers
20        5         142711                 28            5      smoke
21        4           1452                 78            5      smoke
22        5         139236                 70            5      smoke
23        4           1453                 78            5      smoke

    usd_expected usd_actual
0       4.047076       None
1       0.104936       None
2       8.509389       None
3       0.105020       None
4       0.288963       None
5       0.105120       None
6     110.944026       None
7       0.105039       None
8       1.058578       None
9       0.179293       None
10      0.104907       None
11      0.162320       None
12      3.836624       None
13      0.104945       None
14      0.143046       None
15      4.394868       None
16      0.105280       None
17      1.782484       None
18      0.070703       None
19      0.105143       None
20      0.021423       None
21      0.000265       None
22      0.279312       None
23      0.000265       None  , by_stage=  experiment  n_cells_expected  scientific_claim  usd_expected usd_actual
0      smoke               2.0             False        0.3013       None
1   baseline               4.0              True      124.2096       None
2    writers               4.0              True       12.0482       None
3     parked               NaN             False      632.4180       None, parked=                memory_method     role             model        cell_model  \
0                         rag   reader  claude-fable-5-1  claude-fable-5-1
1                         rag    judge       gpt-4o-mini  claude-fable-5-1
2                full_context   reader  claude-fable-5-1  claude-fable-5-1
3                full_context    judge       gpt-4o-mini  claude-fable-5-1
4   teacher_session_summaries   reader  claude-fable-5-1  claude-fable-5-1
5   teacher_session_summaries  teacher  claude-fable-5-1  claude-fable-5-1
6   teacher_session_summaries    judge       gpt-4o-mini  claude-fable-5-1
7               teacher_graph   reader  claude-fable-5-1  claude-fable-5-1
8               teacher_graph  teacher  claude-fable-5-1  claude-fable-5-1
9               teacher_graph    judge       gpt-4o-mini  claude-fable-5-1
10               full_context   reader  claude-fable-5-1  claude-fable-5-1
11               full_context    judge       gpt-4o-mini  claude-fable-5-1

    n_calls  prompt_tokens  completion_tokens  n_questions experiment  \
0      1986        1859606              27322         1986   baseline
1      1540         576372              30800         1986   baseline
2      1986       55304493              27920         1986   baseline
3      1540         577061              30800         1986   baseline
4      1986        1039528              10651         1986    writers
5       272         253618             277449         1986    writers
6      1540         576433              30800         1986    writers
7      1986         898982              13665         1986    writers
8       272         526266             278528         1986    writers
9      1540         578664              30800         1986    writers
10        5         139236                 70            5      smoke
11        4           1453                 78            5      smoke

           usd  launched     parked_id      display_name
0    19.962160     False  claude_fable  Claude Fable 5.1
1     0.104936     False  claude_fable  Claude Fable 5.1
2   554.440930     False  claude_fable  Claude Fable 5.1
3     0.105039     False  claude_fable  Claude Fable 5.1
4    10.927830     False  claude_fable  Claude Fable 5.1
5    16.408630     False  claude_fable  Claude Fable 5.1
6     0.104945     False  claude_fable  Claude Fable 5.1
7     9.673070     False  claude_fable  Claude Fable 5.1
8    19.189060     False  claude_fable  Claude Fable 5.1
9     0.105280     False  claude_fable  Claude Fable 5.1
10    1.395860     False  claude_fable  Claude Fable 5.1
11    0.000265     False  claude_fable  Claude Fable 5.1  , csv_paths=[WindowsPath('C:/home/research/Distillation/distillation/experiments/_campaign/2026_openai_deepseek/analysis/tables/cost_by_cell.csv'), WindowsPath('C:/home/research/Distillation/distillation/experiments/_campaign/2026_openai_deepseek/analysis/tables/cost_by_stage.csv'), WindowsPath('C:/home/research/Distillation/distillation/experiments/_campaign/2026_openai_deepseek/analysis/tables/cost_parked.csv')], plot_paths=[WindowsPath('C:/home/research/Distillation/distillation/experiments/_campaign/2026_openai_deepseek/analysis/plots/cost_by_cell.png'), WindowsPath('C:/home/research/Distillation/distillation/experiments/_campaign/2026_openai_deepseek/analysis/plots/cost_by_stage.png')])

## Post-test

Finished-pack metrics plus expected vs actual USD. Missing packs are skipped, not fatal.

In [ ]:
report = render_campaign(camp, root=ROOT)
print(f"campaign:{camp.id} -> {report.out_dir}")
notebook_posttest(camp, report=report, root=ROOT)